# Generated by Django 3.2.9 on 2022-01-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffordFormular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=120)),
                ('transtype', models.CharField(choices=[('Earning', 'earning'), ('Deduction', 'deduction')], max_length=80)),
                ('transname', models.CharField(max_length=120)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.company')),
            ],
        ),
    ]
