# Generated by Django 3.2.8 on 2021-11-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='faab', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='company_branch',
            field=models.CharField(default='head office', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gra_tin',
            field=models.CharField(default='0', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(default='0', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='ssnit_number',
            field=models.CharField(default='0', max_length=13),
            preserve_default=False,
        ),
    ]
