# Generated by Django 3.2.8 on 2021-11-02 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_auto_20211101_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affordability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20)),
                ('staff_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('ssf_number', models.CharField(max_length=13)),
                ('monthly_afford', models.DecimalField(decimal_places=2, max_digits=8)),
                ('running_afford', models.DecimalField(decimal_places=2, max_digits=8)),
                ('period', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0', max_length=39)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('attempts', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('description', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
