# Generated by Django 3.2.8 on 2021-11-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_activitylog_affordability_loginattempts_usergroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroups',
            old_name='user_id',
            new_name='username',
        ),
    ]
