# Generated by Django 3.2.8 on 2021-11-03 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0004_rename_user_id_usergroups_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='description',
            new_name='activity',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='agent',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='module',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='remote_addr',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='request_uri',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='username',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
    ]
