# Generated by Django 3.2.8 on 2021-11-04 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0005_auto_20211103_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('contact_numbe1', models.CharField(max_length=30)),
                ('contact_number2', models.CharField(max_length=30)),
                ('ceo_number', models.CharField(max_length=30)),
                ('ceo_name', models.CharField(max_length=120)),
                ('contact_person', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=150)),
                ('postal_address', models.CharField(max_length=150)),
                ('landmark', models.CharField(max_length=200)),
                ('authorization_status', models.BooleanField()),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('expiredate', models.DateTimeField()),
                ('verified', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company')),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.companybranch'),
        ),
    ]
