# Generated by Django 3.2.8 on 2021-11-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20211104_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affordability',
            name='employee_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.employee'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=30)),
                ('ghloxid', models.CharField(max_length=30)),
                ('transtype', models.CharField(choices=[('Earning', 'earning'), ('Deduction', 'deduction')], max_length=80)),
                ('transname', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.employee')),
            ],
        ),
    ]
