# Generated by Django 3.2.8 on 2021-11-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20211104_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact_numbe1',
            new_name='contact_number1',
        ),
    ]
