# Generated by Django 3.2.9 on 2021-11-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='authorization_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
