# Generated by Django 3.2.9 on 2021-11-28 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0013_element_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acc_no', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.bank')),
                ('bank_branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.bankbranch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.elementcategory')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='alias',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.company')),
                ('element_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.element')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAdvNo', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('authority_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.authoritynote')),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company')),
                ('element_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.element')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Rejections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company')),
                ('elementcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.element')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.company')),
            ],
        ),
        migrations.AddField(
            model_name='authoritynote',
            name='compid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company'),
        ),
    ]
