# Generated by Django 3.2.9 on 2021-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menumanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
