# Generated by Django 3.2.9 on 2021-11-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menumanager', '0002_alter_menugroup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menugpcode', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('namespace', models.CharField(max_length=255)),
                ('icons', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('0', 'Disable'), ('1', 'Enable')], default='1', max_length=20)),
            ],
        ),
    ]
