# Generated by Django 3.2.9 on 2021-11-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menumanager', '0003_menusubgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSubGroupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('menugpcode', models.CharField(blank=True, max_length=50, null=True)),
                ('menucatcode', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('icons', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('imageuniname', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('0', 'Disable'), ('1', 'Enable')], default='1', max_length=20)),
                ('notification', models.CharField(choices=[('0', 'No notification icon'), ('1', 'Notification icon')], default='0', max_length=20)),
                ('sidebar', models.CharField(choices=[('0', 'Off'), ('1', 'On')], default='1', max_length=20)),
                ('dashboard', models.CharField(choices=[('0', 'Off'), ('1', 'On')], default='1', max_length=20)),
                ('windview', models.CharField(choices=[('0', 'Off'), ('1', 'On')], default='0', max_length=20)),
                ('windviewgeneralreport', models.CharField(blank=True, choices=[('0', 'Off'), ('1', 'On')], max_length=20, null=True)),
                ('windviewfinancialreport', models.CharField(blank=True, choices=[('0', 'Off'), ('1', 'On')], max_length=20, null=True)),
                ('windviewstatisticalreport', models.CharField(blank=True, choices=[('0', 'Off'), ('1', 'On')], max_length=20, null=True)),
                ('admin_accessright', models.CharField(choices=[('1', 'General User'), ('2', 'Administrator Access Right. (Manage Settlement Account) Reserved for Facility administrators')], default='1', max_length=250)),
                ('targeted', models.CharField(max_length=255)),
                ('viewer', models.CharField(max_length=255)),
            ],
        ),
    ]
