# Generated by Django 3.2.9 on 2021-11-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menumanager', '0004_menusubgroupdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubgroupdetail',
            name='targeted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menusubgroupdetail',
            name='viewer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
