# Generated by Django 3.2.9 on 2021-11-09 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menumanager', '0006_menusubgroup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSubUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('menudetcode', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('0', 'Revoked'), ('1', 'Granted')], default='1', max_length=50)),
                ('addedby', models.CharField(blank=True, max_length=50, null=True)),
                ('usruserid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DaUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('startdate', models.DateField(auto_created=True, auto_now=True)),
                ('brchid', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('othernames', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=50)),
                ('emergencyphone', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, choices=[('1', 'administrator'), ('2', 'operator'), ('3', 'Manager')], default='2', max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('-1', 'Deleted'), ('0', 'Disabled'), ('1', 'Enabled')], default='1', max_length=50)),
                ('actorid', models.IntegerField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
