# Generated by Django 3.2.9 on 2021-11-09 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menumanager', '0007_dausers_menusubusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('menudetcode', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', 'Revoked'), ('1', 'Granted')], default='0', max_length=50)),
                ('addedby', models.CharField(blank=True, max_length=50, null=True)),
                ('usruserid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
