# Generated by Django 3.2.9 on 2021-11-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0009_alter_employee_middle_name'),
        ('menumanager', '0008_userspermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dausers',
            name='backenduser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dausers',
            name='companyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payroll.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dausers',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
