# Generated by Django 3.2.9 on 2022-01-17 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menumanager', '0010_alter_menusubusers_usruserid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evtcode', models.CharField(max_length=50)),
                ('memid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('activities', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=200)),
                ('browser', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='dausers',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userspermission',
            name='usruserid',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='MenuUserElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eltuserid', models.CharField(max_length=50)),
                ('eltid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
