# Generated by Django 3.2.9 on 2021-11-17 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0011_bank_bankbranch_element_elementcategory_elementgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CiAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_role_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField()),
                ('is_verify', models.IntegerField(default=1)),
                ('is_admin', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(default=0)),
                ('is_super', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=255)),
                ('password_reset_code', models.CharField(blank=True, max_length=255, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company')),
                ('sysuserid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
