# Generated by Django 3.2.9 on 2021-11-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiAdminRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField()),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
