# Generated by Django 3.2.9 on 2021-11-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0002_ciadminroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('controller_name', models.CharField(max_length=200)),
                ('fa_icon', models.CharField(max_length=100)),
                ('operation', models.TextField()),
                ('sort_order', models.IntegerField()),
            ],
        ),
    ]
