# Generated by Django 3.2.9 on 2022-01-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20220117_2020'),
        ('compapp', '0004_moduleaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciadmin',
            old_name='company_id',
            new_name='compid',
        ),
        migrations.AddField(
            model_name='ciadminroles',
            name='compid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='compid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduleaccess',
            name='compid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciadminroles',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ciadminroles',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleaccess',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compapp.module'),
        ),
    ]
